import pytest

from pydantic_core import ValidationError

from aegis_ai.agents import rh_feature_agent
from aegis_ai.features import component, cve
from aegis_ai.features.cve import QualityReview
from aegis_ai.features.cve.data_models import (
    CATEGORY_WEIGHTS,
    RATING_EXCELLENT,
    RATING_FAILS_STANDARDS,
    RATING_GOOD,
    RATING_NEEDS_IMPROVEMENT,
)
from tests.utils.llm_cache import get_cached_response, cache_response

pytestmark = pytest.mark.asyncio


async def test_suggest_impact_with_test_model():
    test_name = "test_suggest_impact_with_test_model"

    # Try to get cached response first
    result = get_cached_response(test_name)

    if not result:
        # Make real LLM call and cache the response
        llm_result = await cve.SuggestImpact(rh_feature_agent).exec("CVE-2025-0725")
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    suggestimpact = cve.SuggestImpactModel.model_validate_json(result)
    assert isinstance(suggestimpact, cve.SuggestImpactModel)
    assert suggestimpact.impact == "LOW"
    assert (
        suggestimpact.disclaimer
        == "This response was generated by Aegis AI (https://github.com/RedHatProductSecurity/aegis-ai) using generative AI for informational purposes. All findings should be validated by a human expert."
    )


async def test_suggest_cwe_with_test_model(set_test_allowed_cwe_ids_env_var):
    test_name = "test_suggest_cwe_with_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.SuggestCWE(rh_feature_agent).exec("CVE-2025-0725")
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    suggestcwe = cve.SuggestCWEModel.model_validate_json(result)
    assert isinstance(suggestcwe, cve.SuggestCWEModel)
    assert suggestcwe.cwe == ["CWE-190"]


async def test_identify_pii_with_test_model():
    test_name = "test_identify_pii_with_test_model"
    cve_id = "CVE-2025-0725"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.IdentifyPII(rh_feature_agent).exec(cve_id)
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    piireport = cve.PIIReportModel.model_validate_json(result)
    assert isinstance(piireport, cve.PIIReportModel)
    assert not piireport.contains_PII  # is false


async def test_suggest_description_with_test_model():
    test_name = "test_suggest_description_with_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.SuggestDescriptionText(rh_feature_agent).exec(
            "CVE-2025-0725"
        )
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    suggestdescription = cve.SuggestDescriptionModel.model_validate_json(result)
    assert isinstance(suggestdescription, cve.SuggestDescriptionModel)
    assert (
        suggestdescription.suggested_title
        == "libcurl: gzip decompression buffer overflow"
    )


async def test_suggest_statement_with_test_model():
    test_name = "test_suggest_statement_with_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.SuggestStatementText(rh_feature_agent).exec(
            "CVE-2025-0725"
        )
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    suggeststatement = cve.SuggestStatementModel.model_validate_json(result)
    assert isinstance(suggeststatement, cve.SuggestStatementModel)
    assert (
        suggeststatement.suggested_statement
        == "This issue has a low impact on Red Hat products as it only affects libcurl when used with zlib versions 1.2.0.3 or older, which are not widely present in affected Red Hat components. The vulnerability requires specific conditions for exploitation related to automatic gzip decompression."
    )


async def test_cvss_diff_explain_with_test_model():
    test_name = "test_cvss_diff_explain_with_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.CVSSDiffExplainer(rh_feature_agent).exec("CVE-2025-0725")
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    cvssdiffexplain = cve.CVSSDiffExplainerModel.model_validate_json(result)
    assert isinstance(cvssdiffexplain, cve.CVSSDiffExplainerModel)
    assert (
        cvssdiffexplain.redhat_cvss3_vector
        == "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
    )


async def test_component_intelligence_test_model():
    test_name = "test_component_intelligence_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await component.ComponentIntelligence(rh_feature_agent).exec(
            "curl"
        )
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    componentintelligence = component.ComponentIntelligenceModel.model_validate_json(
        result
    )
    assert isinstance(componentintelligence, component.ComponentIntelligenceModel)
    assert componentintelligence.popularity_score == 1
    assert componentintelligence.confidence == 0.95


async def test_quality_review_with_test_model():
    test_name = "test_quality_review_with_test_model"

    result = get_cached_response(test_name)

    if not result:
        llm_result = await cve.QualityReview(rh_feature_agent).exec("CVE-2025-0725")
        result = llm_result.output.model_dump_json(indent=4)
        cache_response(test_name, result)

    quality_review = cve.QualityReviewModel.model_validate_json(result)
    assert isinstance(quality_review, cve.QualityReviewModel)

    # Enforce exact rubric shape: 30 criteria across 6 categories
    assert len(quality_review.scores) == 30, (
        f"Expected 30 criterion scores, got {len(quality_review.scores)}"
    )
    categories = {s["category"] for s in quality_review.scores}
    assert categories == set(CATEGORY_WEIGHTS.keys()), (
        f"Categories mismatch: {categories}"
    )

    # Verify all criterion IDs are unique and match the required rubric set
    criterion_ids = {s["criterion_id"] for s in quality_review.scores}
    assert criterion_ids == QualityReview._REQUIRED_CRITERIA, (
        f"Criterion ID mismatch.\n"
        f"Missing: {QualityReview._REQUIRED_CRITERIA - criterion_ids}\n"
        f"Unexpected: {criterion_ids - QualityReview._REQUIRED_CRITERIA}"
    )

    # Verify overall_score bounds and rating alignment
    assert 0.0 <= quality_review.overall_score <= 1.0
    if quality_review.overall_score >= 0.8:
        assert quality_review.rating == RATING_EXCELLENT
    elif quality_review.overall_score >= 0.6:
        assert quality_review.rating == RATING_GOOD
    elif quality_review.overall_score >= 0.4:
        assert quality_review.rating == RATING_NEEDS_IMPROVEMENT
    else:
        assert quality_review.rating == RATING_FAILS_STANDARDS

    # Verify disclaimer matches the mandated text
    assert quality_review.disclaimer == (
        "This response was generated by Aegis AI "
        "(https://github.com/RedHatProductSecurity/aegis-ai) "
        "using generative AI for informational purposes. "
        "All findings should be validated by a human expert."
    )

    # Verify explanation is present and non-empty
    assert quality_review.explanation, "explanation field must be non-empty"

    # Verify customer lens fields are populated
    assert len(quality_review.customer_can_decide) > 0
    assert len(quality_review.remains_unclear) > 0
    assert len(quality_review.manual_context_needed) > 0


class TestBuildCveInput:
    """Tests for _build_cve_input() helper that populates prompt context."""

    def test_no_static_context(self):
        result = cve._build_cve_input("CVE-2025-1234")
        assert result.cve_id == "CVE-2025-1234"
        assert result.title is None
        assert result.description is None
        assert result.cwe_id is None
        assert result.components is None

    def test_all_osidb_fields_forwarded(self):
        ctx = {
            "title": "kernel: buffer overflow",
            "cve_description": "A flaw was found in the kernel.",
            "cwe_id": "CWE-120",
            "impact": "IMPORTANT",
            "statement": "Red Hat is aware.",
            "mitigation": "Disable the module.",
            "comment_zero": "Buffer overflow in net subsystem.",
            "comments": "Additional context.",
            "components": ["kernel"],
            "references": [{"url": "https://example.com"}],
            "affects": [{"ps_module": "rhel-9"}],
            "cvss_scores": [
                {
                    "issuer": "RH",
                    "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                }
            ],
        }
        result = cve._build_cve_input("CVE-2025-1234", ctx)
        assert result.cve_id == "CVE-2025-1234"
        assert result.title == "kernel: buffer overflow"
        assert result.description == "Buffer overflow in net subsystem."
        assert result.cwe_id == "CWE-120"
        assert result.impact == "IMPORTANT"
        assert result.statement == "Red Hat is aware."
        assert result.mitigation == "Disable the module."
        assert result.comment_zero == "Buffer overflow in net subsystem."
        assert result.comments == "Additional context."
        assert result.components == ["kernel"]
        assert result.references == [{"url": "https://example.com"}]
        assert result.affects == [{"ps_module": "rhel-9"}]
        assert result.cvss_scores is not None and len(result.cvss_scores) == 1

    def test_description_fallback_to_cve_description(self):
        ctx = {"cve_description": "NVD description text."}
        result = cve._build_cve_input("CVE-2025-1234", ctx)
        assert result.description == "NVD description text."

    def test_description_precedence_comment_zero_wins(self):
        ctx = {
            "comment_zero": "from comment_zero",
            "cve_description": "from cve_description",
            "description": "from description",
        }
        result = cve._build_cve_input("CVE-2025-1234", ctx)
        assert result.description == "from comment_zero"

    def test_description_precedence_cve_description_over_description(self):
        ctx = {
            "cve_description": "from cve_description",
            "description": "from description",
        }
        result = cve._build_cve_input("CVE-2025-1234", ctx)
        assert result.description == "from cve_description"

    def test_description_fallback_to_description_key(self):
        ctx = {"description": "from description"}
        result = cve._build_cve_input("CVE-2025-1234", ctx)
        assert result.description == "from description"

    def test_non_dict_static_context_none(self):
        result = cve._build_cve_input("CVE-2025-1234", None)
        assert result.cve_id == "CVE-2025-1234"
        assert result.title is None
        assert result.description is None

    def test_non_dict_static_context_list(self):
        result = cve._build_cve_input("CVE-2025-1234", ["unexpected", "list"])
        assert result.cve_id == "CVE-2025-1234"
        assert result.title is None
        assert result.description is None

    def test_repr_omits_none_fields(self):
        inp = cve.CVEFeatureInput(cve_id="CVE-2025-1234", title="Test")
        r = repr(inp)
        assert "cve_id=" in r
        assert "title=" in r
        assert "None" not in r
        assert "components" not in r


async def test_suggest_impact_with_bad_cve_test_model():
    with pytest.raises(ValidationError) as excinfo:
        await cve.SuggestImpact(rh_feature_agent).exec("BAD-CVE-ID")

    assert "String should match pattern" in str(excinfo)
