"""
Unit tests for the kernel_panic flag pipeline.

Covers:
- FLAG_TO_LABEL mapping and flags population on SuggestImpactModel
- aegis_meta.kernel_flags persistence in suggest_impact()
- FlawCollaborator label creation in FlawUpdater.do()
"""

import pytest
from datetime import datetime, timezone
from types import SimpleNamespace
from unittest.mock import AsyncMock, MagicMock, patch

from aegis_ai.features.cve import SuggestImpact, _FLAG_TO_LABEL
from aegis_ai.features.cve.data_models import SuggestImpactModel
from aegis_ai.osidb_bot.bot import FlawUpdater


pytestmark = pytest.mark.asyncio


CVE_ID = "CVE-2025-99999"

_DISCLAIMER = (
    "This response was generated by Aegis AI "
    "(https://github.com/RedHatProductSecurity/aegis-ai) "
    "using generative AI for informational purposes. "
    "All findings should be validated by a human expert."
)


def _base_model_kwargs(**overrides):
    """Common kwargs required by AegisFeatureModel base class."""
    defaults = {
        "cve_id": CVE_ID,
        "title": "test",
        "explanation": "test",
        "impact": "LOW",
        "cvss3_score": "3.7",
        "cvss3_vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
        "data_quality": 0.9,
        "confidence": 0.9,
        "tools_used": ["osidb_tool"],
        "disclaimer": _DISCLAIMER,
    }
    defaults.update(overrides)
    return defaults


class TestFlagToLabelMapping:
    """Verify the allow-list mapping from classifier features to label names."""

    def test_kernel_panic_maps_to_kpanic(self):
        assert _FLAG_TO_LABEL["kernel_panic"] == "kpanic"

    def test_kernel_panic_plus_uaf_maps_to_kpanic(self):
        assert _FLAG_TO_LABEL["kernel_panic_plus_uaf"] == "kpanic"

    def test_unknown_feature_not_in_mapping(self):
        assert "use_after_free" not in _FLAG_TO_LABEL
        assert "overflow" not in _FLAG_TO_LABEL


class TestSuggestImpactModelFlags:
    """Verify the _flags private attr on SuggestImpactModel."""

    def test_flags_defaults_to_empty_list(self):
        model = SuggestImpactModel(**_base_model_kwargs())
        assert model._flags == []

    def test_flags_not_in_json_schema(self):
        schema = SuggestImpactModel.model_json_schema()
        assert "flags" not in schema.get("properties", {})
        assert "_flags" not in schema.get("properties", {})

    def test_flags_not_in_model_dump(self):
        model = SuggestImpactModel(**_base_model_kwargs())
        model._flags = ["kpanic"]
        dumped = model.model_dump()
        assert "flags" not in dumped
        assert "_flags" not in dumped

    def test_flags_settable_after_construction(self):
        model = SuggestImpactModel(**_base_model_kwargs())
        model._flags = ["kpanic"]
        assert model._flags == ["kpanic"]


def _minimal_flaw_data() -> dict:
    """Build minimal flaw_data that passes FlawFinder.validate()."""
    return {
        "aegis_meta": {},
        "affects": [],
        "classification": {"workflow": "DEFAULT", "state": "NEW"},
        "comment_zero": "",
        "comments": [],
        "components": [],
        "created_dt": "2025-01-01T00:00:00Z",
        "cve_description": "",
        "cve_id": CVE_ID,
        "cvss_scores": [],
        "cwe_id": "",
        "embargoed": False,
        "impact": "",
        "mitigation": "",
        "owner": "",
        "references": [],
        "source": "CVEORG",
        "statement": "",
        "title": "",
        "updated_dt": "2025-01-01T00:00:00Z",
        "uuid": "00000000-0000-0000-0000-000000000099",
    }


def _mock_session(flaw_data: dict) -> MagicMock:
    session = MagicMock()
    session.flaws.retrieve.return_value = MagicMock(to_dict=lambda: flaw_data)
    session.status.return_value = MagicMock(
        dt=datetime(2025, 6, 1, 12, 0, 0, tzinfo=timezone.utc)
    )
    session.flaws.update = MagicMock()
    session.flaws.cvss_scores = MagicMock()
    session.flaws.cvss_scores.create = MagicMock()
    session.flaws.labels = MagicMock()
    session.flaws.labels.create = MagicMock()
    return session


async def _canned_exec_feature_with_flags(feature, flaw_data):
    """Fake exec_feature returning a SuggestImpact output with kernel flags."""
    name = feature.__class__.__name__

    if name == "SuggestAffectedComponents":
        return SimpleNamespace(
            components=["kernel"],
            ecosystems=[],
            explanation="test",
            data_quality=0.9,
            confidence=0.9,
        )
    if name == "SuggestDescriptionText":
        return SimpleNamespace(
            suggested_title="Test title",
            suggested_description="Test desc.",
            explanation="test",
            data_quality=0.9,
            confidence=0.9,
        )
    if name == "SuggestCWE":
        return SimpleNamespace(
            cwe=["CWE-416"],
            explanation="test",
            data_quality=0.9,
            confidence=0.9,
        )
    if name == "SuggestImpact":
        return SimpleNamespace(
            impact="IMPORTANT",
            cvss3_score="7.0",
            cvss3_vector="CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
            explanation="Kernel panic detected",
            data_quality=0.9,
            confidence=0.9,
            _flags=["kpanic"],
        )
    raise ValueError(f"Unknown feature: {name}")


class TestSuggestImpactExecFlagsPopulation:
    """Verify that SuggestImpact.exec() populates _flags from classifier active_features."""

    @patch("aegis_ai.features.cve.SuggestImpact.post_process", return_value="")
    @patch("aegis_ai.features.cve.is_kernel_component", return_value=True)
    @patch("aegis_ai.features.cve.get_settings")
    async def test_known_features_mapped_and_deduped(
        self, mock_settings, _mock_kernel, _mock_pp
    ):
        mock_settings.return_value = MagicMock(use_kernel_classifier=True)

        model = SuggestImpactModel(**_base_model_kwargs())
        mock_result = SimpleNamespace(output=model)

        feature = SuggestImpact(MagicMock())
        classifier = {
            "active_features": [
                "kernel_panic",
                "kernel_panic_plus_uaf",
            ],
        }

        with (
            patch.object(
                feature, "guarded_run", new_callable=AsyncMock, return_value=mock_result
            ),
            patch(
                "aegis_ai.toolsets.tools.kernel_classifier.kernel_impact_classify",
                new_callable=AsyncMock,
                return_value=classifier,
            ),
        ):
            result = await feature.exec(
                CVE_ID,
                static_context={
                    "cvss_scores": [],
                    "components": ["kernel"],
                    "comment_zero": "test",
                },
            )

        assert result.output._flags == ["kpanic"]

    @patch("aegis_ai.features.cve.SuggestImpact.post_process", return_value="")
    @patch("aegis_ai.features.cve.is_kernel_component", return_value=True)
    @patch("aegis_ai.features.cve.get_settings")
    async def test_unknown_features_ignored(
        self, mock_settings, _mock_kernel, _mock_pp
    ):
        mock_settings.return_value = MagicMock(use_kernel_classifier=True)

        model = SuggestImpactModel(**_base_model_kwargs())
        mock_result = SimpleNamespace(output=model)

        feature = SuggestImpact(MagicMock())
        classifier = {
            "active_features": ["overflow", "use_after_free"],
        }

        with (
            patch.object(
                feature, "guarded_run", new_callable=AsyncMock, return_value=mock_result
            ),
            patch(
                "aegis_ai.toolsets.tools.kernel_classifier.kernel_impact_classify",
                new_callable=AsyncMock,
                return_value=classifier,
            ),
        ):
            result = await feature.exec(
                CVE_ID,
                static_context={
                    "cvss_scores": [],
                    "components": ["kernel"],
                    "comment_zero": "test",
                },
            )

        assert result.output._flags == []

    @patch("aegis_ai.features.cve.SuggestImpact.post_process", return_value="")
    @patch("aegis_ai.features.cve.is_kernel_component", return_value=True)
    @patch("aegis_ai.features.cve.get_settings")
    async def test_mixed_known_and_unknown_features(
        self, mock_settings, _mock_kernel, _mock_pp
    ):
        mock_settings.return_value = MagicMock(use_kernel_classifier=True)

        model = SuggestImpactModel(**_base_model_kwargs())
        mock_result = SimpleNamespace(output=model)

        feature = SuggestImpact(MagicMock())
        classifier = {
            "active_features": [
                "kernel_panic",
                "overflow",
                "kernel_panic_plus_uaf",
                "use_after_free",
            ],
        }

        with (
            patch.object(
                feature, "guarded_run", new_callable=AsyncMock, return_value=mock_result
            ),
            patch(
                "aegis_ai.toolsets.tools.kernel_classifier.kernel_impact_classify",
                new_callable=AsyncMock,
                return_value=classifier,
            ),
        ):
            result = await feature.exec(
                CVE_ID,
                static_context={
                    "cvss_scores": [],
                    "components": ["kernel"],
                    "comment_zero": "test",
                },
            )

        assert result.output._flags == ["kpanic"]


class TestSuggestImpactAegisMetaKernelFlags:
    """Test that suggest_impact() writes kernel_flags to aegis_meta."""

    @patch("aegis_ai.osidb_bot.suggest.exec_feature", new_callable=AsyncMock)
    async def test_kernel_flags_persisted_in_aegis_meta(self, mock_exec):
        mock_exec.side_effect = _canned_exec_feature_with_flags

        flaw_data = _minimal_flaw_data()
        from aegis_ai.osidb_bot.suggest import suggest_impact

        ts = datetime(2025, 6, 1, 12, 0, 0, tzinfo=timezone.utc)
        agent = MagicMock()
        changed = await suggest_impact(agent, flaw_data, ts)

        assert "kernel_flags" in changed
        entries = flaw_data["aegis_meta"]["kernel_flags"]
        assert len(entries) == 1
        assert entries[0]["type"] == "AI-Bot"
        assert entries[0]["value"] == ["kpanic"]
        assert entries[0]["timestamp"] == ts.isoformat()

    @patch("aegis_ai.osidb_bot.suggest.exec_feature", new_callable=AsyncMock)
    async def test_no_kernel_flags_when_empty(self, mock_exec):
        """No kernel_flags key when output._flags is empty."""

        async def _no_flags(feature, flaw_data):
            name = feature.__class__.__name__
            if name == "SuggestImpact":
                return SimpleNamespace(
                    impact="MODERATE",
                    cvss3_score="5.5",
                    cvss3_vector="CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                    explanation="test",
                    data_quality=0.9,
                    confidence=0.9,
                    _flags=[],
                )
            return await _canned_exec_feature_with_flags(feature, flaw_data)

        mock_exec.side_effect = _no_flags

        flaw_data = _minimal_flaw_data()
        from aegis_ai.osidb_bot.suggest import suggest_impact

        ts = datetime(2025, 6, 1, 12, 0, 0, tzinfo=timezone.utc)
        changed = await suggest_impact(MagicMock(), flaw_data, ts)

        assert "kernel_flags" not in changed
        assert "kernel_flags" not in flaw_data.get("aegis_meta", {})


class TestFlawUpdaterLabelCreation:
    """Test that FlawUpdater.do() creates alias labels for kernel_flags."""

    @patch("aegis_ai.osidb_bot.suggest.exec_feature", new_callable=AsyncMock)
    async def test_labels_created_for_kernel_flags(self, mock_exec):
        mock_exec.side_effect = _canned_exec_feature_with_flags

        flaw_data = _minimal_flaw_data()
        session = _mock_session(flaw_data)
        agent = MagicMock()

        updater = FlawUpdater(session, agent, CVE_ID)
        await updater.do()

        # Verify labels.create was called with kpanic
        session.flaws.labels.create.assert_called_once_with(
            flaw_id="00000000-0000-0000-0000-000000000099",
            form_data={
                "label": "kpanic",
                "type": "alias",
                "state": "NEW",
            },
        )

    @patch("aegis_ai.osidb_bot.suggest.exec_feature", new_callable=AsyncMock)
    async def test_label_creation_failure_does_not_crash(self, mock_exec):
        """A failed label creation is logged but doesn't abort the update."""
        mock_exec.side_effect = _canned_exec_feature_with_flags

        flaw_data = _minimal_flaw_data()
        session = _mock_session(flaw_data)
        session.flaws.labels.create.side_effect = RuntimeError("OSIDB 500")
        agent = MagicMock()

        updater = FlawUpdater(session, agent, CVE_ID)
        await updater.do()

        # The flaw update itself should still have succeeded
        session.flaws.update.assert_called_once()
        # kernel_flags should be removed from updated_fields on failure
        assert "kernel_flags" not in updater.updated_fields
