import pytest

from pydantic import ValidationError

from aegis_ai.features.cve.data_models import (
    CATEGORY_WEIGHTS,
    CriterionScore,
    CustomerLensAssessment,
    QualityRating,
    QualityReviewModel,
)

DISCLAIMER = (
    "This response was generated by Aegis AI "
    "(https://github.com/RedHatProductSecurity/aegis-ai) "
    "using generative AI for informational purposes. "
    "All findings should be validated by a human expert."
)

_CATEGORY_NAMES = [
    "Description - Technical Clarity",
    "Statement - Technical Clarity",
    "Mitigation",
    "Grammar & Style",
    "Content Ambiguity",
    "Technical Value",
]

_CRITERION_IDS = [
    "criterion_0",
    "criterion_1",
    "criterion_2",
    "criterion_3",
    "criterion_4",
]


def _make_scores(category_scores: list[list[int]]) -> list[CriterionScore]:
    """Build a flat list of CriterionScore from 6 lists of criterion scores (one per category)."""
    scores = []
    for cat_name, cat_scores in zip(_CATEGORY_NAMES, category_scores):
        for crit_id, s in zip(_CRITERION_IDS, cat_scores):
            scores.append(
                CriterionScore(
                    category=cat_name,
                    criterion_id=crit_id,
                    score=s,
                    justification=f"Justification for {crit_id} in {cat_name}",
                )
            )
    return scores


def _make_review_model(category_scores: list[list[int]]) -> QualityReviewModel:
    """Build a full QualityReviewModel from 6 lists of criterion scores."""
    return QualityReviewModel(
        cve_id="CVE-2025-0001",
        scores=_make_scores(category_scores),
        customer_lens=CustomerLensAssessment(
            customer_can_decide=["Exposure scope"],
            remains_unclear=["Exploit likelihood"],
            manual_context_needed=["Deployment context"],
        ),
        strengths=["Clear description"],
        critical_gaps=["Missing statement"],
        recommendations=["Add a statement"],
        value_add="Provides Red Hat context not available in NVD",
        explanation="Quality review summary for testing.",
        data_quality=0.8,
        confidence=0.7,
        tools_used=["osidb_tool"],
        disclaimer=DISCLAIMER,
    )


# --- CATEGORY_WEIGHTS ---


def test_category_weights_sum_to_one():
    assert round(sum(CATEGORY_WEIGHTS.values()), 2) == 1.0


def test_category_weights_match_spec():
    """Verify weights match the FQI specification."""
    assert CATEGORY_WEIGHTS["Description - Technical Clarity"] == 0.20
    assert CATEGORY_WEIGHTS["Statement - Technical Clarity"] == 0.25
    assert CATEGORY_WEIGHTS["Mitigation"] == 0.10
    assert CATEGORY_WEIGHTS["Grammar & Style"] == 0.15
    assert CATEGORY_WEIGHTS["Content Ambiguity"] == 0.15
    assert CATEGORY_WEIGHTS["Technical Value"] == 0.15


# --- QualityRating enum ---


def test_quality_rating_values():
    assert QualityRating.EXCELLENT.value == "Excellent"
    assert QualityRating.GOOD.value == "Good"
    assert QualityRating.NEEDS_IMPROVEMENT.value == "Needs Improvement"
    assert QualityRating.FAILS_STANDARDS.value == "Fails Standards"


# --- CriterionScore validation ---


def test_criterion_score_valid():
    cs = CriterionScore(
        category="Test", criterion_id="test", score=1, justification="ok"
    )
    assert cs.score == 1


def test_criterion_score_bounds_low():
    with pytest.raises(ValidationError):
        CriterionScore(
            category="Test", criterion_id="test", score=-1, justification="bad"
        )


def test_criterion_score_bounds_high():
    with pytest.raises(ValidationError):
        CriterionScore(
            category="Test", criterion_id="test", score=3, justification="bad"
        )


# --- QualityReviewModel weighted score and rating ---


def test_quality_review_excellent():
    # All categories score 10/10 raw -> weighted 1.0
    model = _make_review_model([[2, 2, 2, 2, 2]] * 6)
    assert model.overall_score == 1.0
    assert model.rating == QualityRating.EXCELLENT


def test_quality_review_good():
    # All categories 7/10 raw -> weighted 0.7
    model = _make_review_model([[2, 1, 1, 1, 2]] * 6)
    assert model.overall_score == 0.7
    assert model.rating == QualityRating.GOOD


def test_quality_review_needs_improvement():
    # All categories 5/10 raw -> weighted 0.5
    model = _make_review_model([[1, 1, 1, 1, 1]] * 6)
    assert model.overall_score == 0.5
    assert model.rating == QualityRating.NEEDS_IMPROVEMENT


def test_quality_review_fails_standards():
    # All categories 3/10 raw -> weighted 0.3
    model = _make_review_model([[1, 1, 1, 0, 0]] * 6)
    assert model.overall_score == 0.3
    assert model.rating == QualityRating.FAILS_STANDARDS


# --- printable_outcome ---


def test_printable_outcome():
    model = _make_review_model([[2, 2, 2, 2, 2]] * 6)
    assert model.printable_outcome() == "score=1.0/1.0 (Excellent)"


def test_printable_outcome_low_score():
    model = _make_review_model([[0, 0, 0, 0, 0]] * 6)
    assert model.printable_outcome() == "score=0.0/1.0 (Fails Standards)"


# --- Auto-computation ignores LLM-provided values ---


def test_overall_score_ignores_llm_provided_value():
    """overall_score and rating must be auto-computed, ignoring any values the LLM provides."""
    scores = _make_scores([[2, 2, 2, 2, 2]] * 6)

    # Pass wrong overall_score and rating -- they should be overridden
    model = QualityReviewModel(
        cve_id="CVE-2025-0001",
        overall_score=0.1,  # wrong -- should be auto-computed to 1.0
        rating=QualityRating.FAILS_STANDARDS,  # wrong -- should be Excellent
        scores=scores,
        customer_lens=CustomerLensAssessment(
            customer_can_decide=["test"],
            remains_unclear=["test"],
            manual_context_needed=["test"],
        ),
        strengths=["test"],
        critical_gaps=["test"],
        recommendations=["test"],
        value_add="test",
        explanation="test",
        data_quality=0.8,
        confidence=0.7,
        tools_used=["osidb_tool"],
        disclaimer=DISCLAIMER,
    )
    assert model.overall_score == 1.0
    assert model.rating == QualityRating.EXCELLENT


# --- Rating boundary tests ---


def test_rating_boundary_excellent():
    """All categories at 8/10 raw -> weighted 0.8 = Excellent threshold."""
    model = _make_review_model([[2, 2, 2, 2, 0]] * 6)
    assert model.overall_score == 0.8
    assert model.rating == QualityRating.EXCELLENT


def test_rating_boundary_just_below_excellent():
    """5 categories at 8/10, last (Technical Value, 15%) at 7/10 -> 0.79 = Good."""
    cats = [[2, 2, 2, 2, 0]] * 5 + [[2, 2, 2, 1, 0]]
    model = _make_review_model(cats)
    assert model.overall_score == 0.79
    assert model.rating == QualityRating.GOOD


def test_rating_boundary_good():
    """All categories at 6/10 raw -> weighted 0.6 = Good threshold."""
    model = _make_review_model([[2, 2, 2, 0, 0]] * 6)
    assert model.overall_score == 0.6
    assert model.rating == QualityRating.GOOD


def test_rating_boundary_needs_improvement():
    """All categories at 4/10 raw -> weighted 0.4 = Needs Improvement threshold."""
    model = _make_review_model([[2, 2, 0, 0, 0]] * 6)
    assert model.overall_score == 0.4
    assert model.rating == QualityRating.NEEDS_IMPROVEMENT


def test_rating_boundary_just_below_needs_improvement():
    """5 categories at 4/10, last (Technical Value, 15%) at 3/10 -> 0.39 = Fails Standards."""
    cats = [[2, 2, 0, 0, 0]] * 5 + [[2, 1, 0, 0, 0]]
    model = _make_review_model(cats)
    assert model.overall_score == 0.39
    assert model.rating == QualityRating.FAILS_STANDARDS


# --- Weighting verification ---


def test_statement_weight_exceeds_mitigation():
    """Statement (25%) should contribute more than Mitigation (10%) to the final score.

    Two scenarios with identical total raw points but different distributions:
    - A: Statement=10, Mitigation=0 (rest at 5) -> 0.57
    - B: Statement=0, Mitigation=10 (rest at 5) -> 0.43
    """
    # Great statement, no mitigation
    score_a = _make_review_model(
        [
            [1, 1, 1, 1, 1],
            [2, 2, 2, 2, 2],
            [0, 0, 0, 0, 0],
            [1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1],
        ]
    )
    # No statement, great mitigation
    score_b = _make_review_model(
        [
            [1, 1, 1, 1, 1],
            [0, 0, 0, 0, 0],
            [2, 2, 2, 2, 2],
            [1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1],
            [1, 1, 1, 1, 1],
        ]
    )
    assert score_a.overall_score == 0.57
    assert score_b.overall_score == 0.43
    assert score_a.overall_score > score_b.overall_score


# --- Clamping verification ---


def test_category_raw_scores_clamped_to_10():
    """If a category accumulates >10 raw points, the validator clamps to 10.

    Build 6 criteria (12 raw points) for the first category, 5 criteria (0 points)
    for the rest. The first category should contribute as if it scored 10/10.
    """
    first_cat = _CATEGORY_NAMES[0]
    first_cat_weight = CATEGORY_WEIGHTS[first_cat]

    # 6 criteria at score=2 -> 12 raw points, should clamp to 10
    scores = [
        CriterionScore(
            category=first_cat,
            criterion_id=f"extra_{i}",
            score=2,
            justification="test",
        )
        for i in range(6)
    ]
    # Remaining 5 categories with 5 criteria each at score=0
    for cat_name in _CATEGORY_NAMES[1:]:
        for crit_id in _CRITERION_IDS:
            scores.append(
                CriterionScore(
                    category=cat_name,
                    criterion_id=f"{cat_name}_{crit_id}",
                    score=0,
                    justification="test",
                )
            )

    model = QualityReviewModel(
        cve_id="CVE-2025-0001",
        scores=scores,
        customer_lens=CustomerLensAssessment(
            customer_can_decide=["test"],
            remains_unclear=["test"],
            manual_context_needed=["test"],
        ),
        strengths=["test"],
        critical_gaps=["test"],
        recommendations=["test"],
        value_add="test",
        explanation="test",
        data_quality=0.8,
        confidence=0.7,
        tools_used=["osidb_tool"],
        disclaimer=DISCLAIMER,
    )
    # Clamped: (10/10) * first_cat_weight = first_cat_weight
    assert model.overall_score == round(first_cat_weight, 2)
