import datetime
from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel, Field


@dataclass
class feature_deps:
    """
    A dataclass to hold feature data dependencies, including a dynamically
    generated current datetime string.

    These deps are used to dynamically provide information to tooling.
    https://ai.pydantic.dev/dependencies/#defining-dependencies

    """

    current_dt: str = field(
        default_factory=lambda: datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    )
    exclude_osidb_fields: list[str] = field(
        default_factory=list,
    )
    # When set, the OSIDB flaw_tool uses this instead of calling OSIDB API.
    # Used when static_context already contains sufficient CVE data (e.g. from web API).
    static_context: Any | None = field(default=None)
    # Set by SuggestImpact.exec (pre-run) or flaw_tool (at runtime) when OSIDB
    # data indicates a kernel component.  Read by check_kernel_output to
    # enforce kernel_impact_tool usage, and by the tool itself to gate
    # non-kernel calls.
    is_kernel_cve: bool = field(default=False)
    # Incremented by kernel_impact_tool each time the LLM invokes it.
    # check_kernel_output reads this: 0 means the LLM never called the tool
    # (triggers retry), >0 means it tried (accept, even if classifier_result
    # is None).
    classifier_attempts: int = field(default=0)
    # Pre-computed classifier result from kernel_impact_classify.  Set by
    # exec() before the LLM run; kernel_impact_tool returns it immediately
    # via its fast-path cache (mirrors the flaw_tool static_context pattern).
    # Also read by post-processing (reconciliation, guardrails).
    classifier_result: dict | None = field(default=None)


class FeatureQueryInput(BaseModel):
    query: str = Field(..., description="General LLM query.")


class AegisFeatureModel(BaseModel):
    """
    Metadata for Aegis features, nested within the main feature model.
    """

    data_quality: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Amount of technical data in the `comment_zero` input field relevant for generating the requested suggestions, ranging from 0.0 (insufficient) to 1.0 (perfect).",
    )

    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Quantification of reliability of the provided suggestion, ranging from 0.0 (guessing) to 1.0 (certainty).  Be conservative in this judgment.",
    )

    tools_used: list[str] = Field(
        default_factory=list,
        description="Tools that were called during this run (populated automatically, not by the LLM).",
    )

    # Important: This default disclaimer is required by AI assessment - do not change or remove without talking to someone !
    disclaimer: Literal[
        "This response was generated by Aegis AI (https://github.com/RedHatProductSecurity/aegis-ai) using generative AI for informational purposes. All findings should be validated by a human expert."
    ]

    def printable_outcome(self) -> str:
        """this method can be overridden to provide printable outcome for logging purposes"""
        return "[...]"


# this is only used by simple_agent
class AegisAnswer(AegisFeatureModel):
    """
    Default answer response.
    """

    explanation: str = Field(
        ...,
        description="A brief rationale explaining how the answer was generated, what sources were primary, and if the answer was provided directly by the LLM or not. Do not repeat the answer here.",
    )

    answer: str = Field(..., description="The direct answer to the user's question.")
